services:
  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    ports:
      - '3001:3001'

  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
